### ISSUE TITLE
Missing Extras

### ISSUE THREAD

**Issue by BallOpener** [henrikx/metroskininstaller#26] opened 2019-10-08 04:39 UTC
For some reason, the Big Picture + Green Notification Box and Big Picture + Green Notification Icon options are missing from the extras list in the app.

**Comment by PhantomGamers** [comment] 2019-10-08 05:01
This is a dupe of #4

**Comment by henrikx** [comment] 2019-10-09 17:28
duplicate of #4

**Closed as completed by henrikx** 2019-10-09 17:28 UTC
Labels: duplicate
